export enum STORE_TRANSACTION_TYPE {
  EARNING = 'EARNING',
  PAYOUT = 'PAYOUT',
  REFUND = 'REFUND',
}

export enum STORE_TRANSACTION_STATUS {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
